### PR TITLE
Added merge sort file in cpp

### PR DESCRIPTION
**Pull request by Reetesh-Tomar**
Please merge

### CODE REVIEW

**Review by vaibhav4516 — APPROVED** [review]
the Solution is correct. it can be merged. 
Thank You!!
Happy Coding.

**Comment by Reetesh-Tomar** [comment]
Thank you so much

**Review by Nabagata — CHANGES_REQUESTED** [review]
I have to add the submission guideline for adding codes. For now for this PR, please rename the file in kebap case and apply correct formatting to the code using something like https://zed0.co.uk/clang-format-configurator/

**Comment by Reetesh-Tomar** [comment]
Will do, thanks!

**Comment by Reetesh-Tomar** [comment]
Hi sir,
I have added all the changes that need to be done, please notice it and
please merge my contribution.
Thank you so much

**Review by Nabagata — APPROVED** [review]
LGTM

**Pull request merged**
